# -*- coding: utf-8 -*-
"""파이썬 기초(lv1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrNNsQs9baisoJ7WAnj7MOEvHcDNH5lx

### 입/출력, 변수, 연산자, 자료형
"""

print(123)

# 출력과 입력
print(123)
print(456.789)
print(12-4) # print 괄호 안에 수식이 있는 경우에는 수식의 결과값을 출력합니다.
print(12/4)
print(10/3)

print("안녕하세요")
print('고양이가 "야옹"') # 따옴표 출력할 때는 "와 '를 번갈아 씁니다.
print("~!@#$%^&*()_+|;:") # 따옴표를 제외한 특수기호는 그대로 출력 가능합니다.
print("강아지가", "멍"*5) # print() 함수 내부에 콤마 연산자는 두 문자열을 합치고, * 연산자는 문자열을 반복합니다.

print("안녕하세요")

# 변수
score = 95 # 변수 score를 만들고 값 95를 할당합니다.
print(score)
print("점수", score) # print 함수 안에 있는 쉼표(,) 연산자는 두 문자열을 합쳐줍니다.
print("2배 하면", score*2, "점입니다.")

name = "홍길동"
print(name)
print("이름:", name)
print(name, "씨의 이름은", name, "입니다.")

# 산술 연산
a = 7                           # 변수 a에 7을 할당
b = 3                          # 변수 b에 3을 할당

print("a =", a)                # a의 값 출력
print("b =", b)                # b의 값 출력
print("a + b =", a + b)        # 덧셈 연산자: 7 + 3 = 10
print("a - b =", a - b)        # 뺄셈 연산자: 7 - 3 = 4
print("a * b =", a * b)        # 곱셈 연산자: 7 * 3 = 21
print("a / b =", a / b)        # 나눗셈 연산자: 7 / 3 = 2.333...
print("a ** b =", a ** b)      # 거듭제곱 연산자: 7의 3제곱 = 343
print("a // b =", a // b)      # 몫 연산자(정수 나눗셈): 7 // 3 = 2
print("a % b =", a % b)        # 나머지 연산자: 7 % 3 = 1

# 비교연산
a = 7                          # 변수 a에 7을 할당
b = 3                          # 변수 b에 3을 할당

print("a =", a)                # a의 값 출력
print("b =", b)                # b의 값 출력
print("a == b:", a == b)       # 같다(equal to): 7과 3이 같은지 비교
print("a != b:", a != b)       # 같지 않다(not equal to): 7과 3이 다른지 비교
print("a > b:", a > b)         # 크다(greater than): 7이 3보다 큰지 비교
print("a < b:", a < b)         # 작다(less than): 7이 3보다 작은지 비교
print("a >= b:", a >= b)       # 크거나 같다(greater than or equal to): 7이 3보다 크거나 같은지 비교
print("a <= b:", a <= b)       # 작거나 같다(less than or equal to): 7이 3보다 작거나 같은지 비교

print("apple" < "banana") # 문자열 비교는 알파벳 순서에 따라 이루어집니다. a가 가장 작고 z가 가장 큽니다.
print("apple" < "applepie") # 문자열 비교는 알파벳 순서에 따라 이루어집니다. a가 가장 작고 z가 가장 큽니다.

# 할당연산
a = 0                          # 변수 a에 0을 할당
print("a=", a)
a = a + 7
print("a=", a)

a+=2     # a = a + 2
print(a) # 복합 할당 연산자들은 변수에 대해 특정 연산을 수행하고 그 결과를 동일한 변수에 할당합니다.
a-=3     # a = a - 3
print(a)
a*=4     # a = a*4
print(a)
a/=6     # a = a/6
print(a)

# 논리 연산
a = 6
print("a%2==0", a%2==0) # 참입니다.
print("a%3==0",a%3==0) # 참입니다.
print("a%4==0",a%4==0) # 거짓입니다.

print("a%2==0 and a%3==0", a%2==0 and a%3==0) # 참입니다.
print("a%2==0 and a%4==0", a%2==0 and a%4==0) # 거짓입니다.
print("a%2==0 or a%3==0", a%2==0 or a%3==0) # 참입니다.
print("a%2==0 or a%4==0", a%2==0 or a%4==0) # 참입니다.
print(not(a%2==0)) # 거짓입니다. not 연산자는 참/거짓 값을 반전시키기 때문입니다.

# 숫자형
import math
import random

print("1. 절대값:", abs(-12.34))          # 절대값 계산
print("2. 올림:", math.ceil(3.14))        # 올림 함수 사용
print("3. 내림:", math.floor(3.14))       # 내림 함수 사용
print("4. 반올림:", round(3.1415926535, 2))  # 소수점 2자리까지 반올림

print("5. 실수를 정수로:", int(12.34))     # 실수를 정수로 변환
print("6. 문자열을 정수로:", int("123"))    # 문자열을 정수로 변환

print("7. 랜덤 정수(1~5):", random.randint(1,5))  # 1~5 사이의 랜덤 정수 생성
print("8. 랜덤 실수(0~1):", random.random())      # 0~1 사이의 랜덤 실수 생성
print("9. 랜덤 증가(0~100,10씩):", random.randrange(0,100,10))  # 0~100 사이 10씩 증가하는 수 중 랜덤 선택

print("10. 1 라디안을 각도로:", math.degrees(1))    # 라디안을 각도로 변환
print("11. 90 각도를 라디안으로:", math.radians(90))  # 각도를 라디안으로 변환

print("7. 랜덤 정수(1~5):", random.randint(1,5))  # 1~5 사이의 랜덤 정수 생성
print("8. 랜덤 실수(0~1):", random.random())      # 0~1 사이의 랜덤 실수 생성
print("9. 랜덤 증가(0~100,10씩):", random.randrange(0,100,10))  # 0~100 사이 10씩 증가하는 수 중 랜덤 선택

"""###[0]안 [1]녕   [2]하  [3]세   [4]요  [5]"""

# 문자형

text1 = "안녕하세요"                      # 기본 문자열 변수 선언
print("1.", text1)                        # 문자열 전체 출력
print("2. 첫글자만:", text1[0])           # 문자열의 첫 번째 문자만 출력
print("2. 뒤에서 두번째 글자만:", text1[-2])           # 문자열의 뒤에서 두번째 문자만 출력

print("3. 3번째~4번째 문자:", text1[2:4])  # 문자열 슬라이싱: 3~4번째 문자 출력
print("3. 뭐 나오게?:", text1[1:-1]) # 문자열 슬라이싱: 1~(뒤에서 첫번째 문자) 출력

text2 = """4. 동해물과 백두산이
마르고 닳도록
하느님이 보우하사
우리 나라 만세"""
print(text2)                              # 여러 줄 문자열 출력 (따옴표 3개 사용)

print("5. 이것은\n한줄씩\n줄바꿈")         # \n을 사용한 줄바꿈 예시
print("6. 이것은\t탭으로\t띄우기")         # \t를 사용한 탭 간격 예시

print("7. 문자열 " , "더하기")             # 문자열 연결(concatenation) 예시
print("7. 문자열 " + "더하기")
print("8. 문자열 " + "복제 "*5)            # 문자열 반복 예시

# 문자열 포매팅
print("9. 이름은 %s이고, 나이는 %d입니다." % ("홍길동", 19))  # % 연산자 방식

name = "앨리스"
age = 30

print("10. 이름은 {}이고, 나이는 {}입니다.".format(name, age)) # format() 함수 방식
print(f"10. 이름은 {name}이고, 나이는 {age}입니다.") # f-string 방식

# 리스트
subject = ["국어", "영어", "수학", "정보"]   # 과목명 리스트 생성
score = [95, 87, 91, 100]                # 점수 리스트 생성

print("1. 과목:", subject)                # 과목 리스트 전체 출력
print("2. 점수:", score)                  # 점수 리스트 전체 출력
print("3. 정보 인덱스 번호:", subject.index("정보"))  # '정보' 과목의 인덱스 찾기
print("4. 점수 첫번째 항목:", score[0])     # 첫 번째 점수 출력
print("5. 정보 과목의 점수 찾기:", score[subject.index("정보")])  # '정보' 과목의 점수 찾기

print("6. 리스트 길이:", len(subject))     # 리스트의 길이 출력
print("7. 리스트 합치기:", subject + score) # 두 리스트 합치기

print("8. 리스트 반복")                    # 리스트 순회 시작
for title in subject:                     # 각 과목에 대해 반복
    print(title, ":", score[subject.index(title)])  # 과목별 점수 출력

# 불리언
print(True)                               # 불리언 값 True 출력
print(3 > 2)                             # 비교 연산 결과 출력
print(bool(1))                           # 0을 불리언으로 변환 (False)
print(bool("a"))                          # 빈 문자열을 불리언으로 변환 (False)
print(6 % 2 == 0 and 6 % 3 == 0)        # 논리 연산 예시 (6이 2와 3의 공배수인지 확인)

isDoorOpen = False                        # 불리언 변수 선언
isUserHasKey = True                       # 불리언 변수 선언

print("자료형:", type(isDoorOpen))         # 변수의 자료형 출력
print("문열림여부:", isDoorOpen)           # 불리언 변수 값 출력
print("키소유여부:", isUserHasKey)         # 불리언 변수 값 출력
print("문 열리고, 키 있음", isDoorOpen and isUserHasKey)  # AND 논리 연산
print("문 안열리고, 키 있음:", not isDoorOpen and isUserHasKey)  # NOT과 AND 복합 논리 연산

a = "안녕"
print(a)

"""### 조건문, 반복문, 함수"""

# 조건문 숫자
score = 2
print("1. 점수:", score)

if score >=3:
    print("2. 3점 이상으로 성공입니다. 엔딩화면으로 이동합니다.")
else:
    print("2. 3점 미만으로 실패입니다. 게임을 재시작합니다.")

# 조건문 문자
other = "도착지점"
abc = "바닥"

print("1. 충돌 가능 오브젝트: 바닥, 도착지점, 장애물")
print("2. 충돌한 대상:", other)
if abc == "바닥":
    print("3. 바닥에 떨어지면 탈락입니다. 게임을 재시작합니다.")
elif other == "도착지점":
    print("3. 도착지점에 도착했습니다. 게임을 종료합니다.")
else:
    print("3. 여기에는 아무것도 없습니다.")

# 반복문 for
for num in range(1,11): # for 문은 반복 범위가 명확할 때 정해진 횟수만큼 반복시키는 문법입니다.
    if num % 2 == 0:
        print(num, "은 짝수입니다.")
    else:
        print(num, "은 홀수입니다.")

# 반복문 while
num = 2
goal = 1000

while True: # while 문은 반복 조건이 동적이거나 불확실할 때 조건이 만족될 때까지 반복시키는 문법입니다.
    print(num)
    if num > goal:
        break
    num *=2

print("반복이 끝났습니다.")
print(goal, "보다 크면서 가장 작은 2의 제곱수는", num, "입니다.")

# 함수 - 특정한 작업을 반복해서 수행하기 위해 사용합니다.
def say():
    print("안녕하세요.")

say()
say()
say()

def say2(num):
    print(num, "번 손님, 안녕하세요.")

say2(1)
say2(1+1)
say2(9/3)

def say3(name):
    print(name, "님 안녕하세요.")

you = 1004
say3("홍길동")
say3("이순신")
say3(you)


def say4(a, b):
    return a + b

say4(1,4)

# 함수 2 - 글로벌 함수
score = 0
print("점수:", score)

def score_up():
    global score
    score += 1 # score = score + 1
    print("점수 증가:", score)

def score_reset():
    global score
    score = 0
    print("점수 초기화:", score)

def new_score_up():
    new_score = score + 1
    print("점수 증가:", new_score)

score_up()
score_up()
score_reset()
score_up()

score_up()

new_score_up()

score_reset()

"""### 클래스"""

# 클래스 정의
class Dog:
    def __init__(self, name, breed):  # 생성자 (초기화 메서드)
        self.name = name  # 인스턴스 변수 name 초기화
        self.breed = breed  # 인스턴스 변수 breed 초기화

    def bark(self):  # 메서드 정의
        print("Woof!")

# 첫 번째 강아지 인스턴스 생성
my_dog1 = Dog("Buddy", "Golden Retriever")

# 두 번째 강아지 인스턴스 생성
my_dog2 = Dog("Coco", "Poodle")

# 각 인스턴스의 속성 출력
print(my_dog1.name, my_dog1.breed)  # 출력: Buddy Golden Retriever
print(my_dog2.name, my_dog2.breed)  # 출력: Coco Poodle

# 각 인스턴스의 메서드 호출
my_dog1.bark()  # 출력: Woof!
my_dog2.bark()  # 출력: Woof!

class Character:  # 캐릭터의 기본 속성을 정의하는 부모 클래스
    def __init__(self, name, hp, power, attack_speed, attack_range): # __init__: 생성자 메서드로, 객체가 생성될 때 자동으로 호출됩니다.
        self.name = name  # self: 객체 자신을 가리키는 참조입니다.
        self.hp = hp  # 캐릭터의 체력
        self.power = power  # 캐릭터의 공격력
        self.attack_speed = attack_speed  # 캐릭터의 공격 속도
        self.attack_range = attack_range  # 캐릭터의 공격 거리
        self.is_alive = True  # 캐릭터의 생존 여부

    def attack(self):
        print(f"{self.name} 공격!")  # 캐릭터의 공격 동작, 기본적으로 "공격!" 메시지 출력

# 기본 캐릭터 인스턴스 생성
hero1 = Character("전사", "300", "50", "30", "2")
hero2 = Character("궁수", "200", "40", "15", "10")

# 기본 캐릭터 정보 출력
print(f"{hero1.name}: 체력 {hero1.hp}, 공격력 {hero1.power}, 공격속도 {hero1.attack_speed}, 공격거리 {hero1.attack_range}")
print(f"{hero2.name}: 체력 {hero2.hp}, 공격력 {hero2.power}, 공격속도 {hero2.attack_speed}, 공격거리 {hero2.attack_range}")

# 공격 메서드 실행
hero1.attack()  # 출력: 이름 생성: 공격!
hero2.attack()  # 출력: 이름 생성: 공격!

class Warrior(Character):  # 도끼병 캐릭터 자식 클래스 (Character 클래스 상속)
    def __init__(self, name):
        super().__init__(name, hp=100, power=80, attack_speed=70, attack_range=20) # super()는 부모 클래스의 메서드들을 호출할 수 있게 해주는 내장 함수

    def attack(self): # 메서드 오버라이딩(Method Overriding) - 부모 클래스의 메서드를 자식 클래스에서 재정의
        print(f"{self.name}: 돌격!")  # 도끼병 캐릭터의 공격 동작, "돌격!" 메시지 출력

class Archer(Character):  # 궁수 캐릭터 클래스 (Character 클래스 상속)
    def __init__(self, name):
        super().__init__(name, hp=50, power=30, attack_speed=30, attack_range=80) # 부모 클래스(Character)의 생성자를 호출, 기본 속성 설정, 낮은 체력, 낮은 공격력, 낮은 공격 속도, 높은 공격 거리

    def attack(self):
        print(f"{self.name}: 발사!")  # 궁수 캐릭터의 공격 동작, "발사!" 메시지 출력

# 캐릭터 인스턴스 생성
warrior1 = Warrior("도끼병")
warrior2 = Warrior("망치병")
archer1 = Archer("궁수")
archer2 = Archer("사수")

# 캐릭터 정보 출력
print(f"{warrior1.name}: 체력 {warrior1.hp}, 공격력 {warrior1.power}, 공격속도 {warrior1.attack_speed}, 공격거리 {warrior1.attack_range}")
print(f"{warrior2.name}: 체력 {warrior2.hp}, 공격력 {warrior2.power}, 공격속도 {warrior2.attack_speed}, 공격거리 {warrior2.attack_range}")
print(f"{archer1.name}: 체력 {archer1.hp}, 공격력 {archer1.power}, 공격속도 {archer1.attack_speed}, 공격거리 {archer1.attack_range}")
print(f"{archer2.name}: 체력 {archer2.hp}, 공격력 {archer2.power}, 공격속도 {archer2.attack_speed}, 공격거리 {archer2.attack_range}")

# 공격 메서드 실행
warrior1.attack()  # 출력: 도끼병: 돌격!
warrior2.attack()  # 출력: 망치병: 돌격!
archer1.attack()  # 출력: 궁수: 발사!
archer2.attack()  # 출력: 사수: 발사!

"""### 모듈

1. 모듈의 기본 개념
- 모듈은 파이썬 코드를 논리적으로 묶어서 관리하고 사용할 수 있게 하는 것
- .py 파일 단위입니다.
- 일반적으로 다른 프로그래밍 언어의 '라이브러리'와 같은 개념입니다.

2. 모듈의 종류
- 표준 모듈: 파이썬에 기본 내장된 모듈
- 외부 모듈: 다른 개발자가 만든 모듈
- 사용자 정의 모듈: 직접 만든 모듈
"""

# 3. 모듈 사용 방법
# 기본 import
import keyword as k  # as로 별칭 지정 가능
print(k.kwlist)

# 특정 기능만 import
from keyword import kwlist # 예약어 리스트
print(kwlist)  # 모듈명 없이 직접 사용 가능

# 4. 주요 표준 모듈
# os 모듈 - 운영체제와 상호작용을 위한 함수들 제공
import os
print(os.getcwd())  # 현재 작업 디렉토리 출력

# time 모듈 - 시간 관련 함수들 제공
import time as t                # time 모듈을 가져옴 - 시간 관련 기능을 사용하기 위한 파이썬 내장 모듈
print(t.localtime())      # 현재 시스템의 로컬 시간을 구조체 형태로 출력 (년,월,일,시,분,초 등의 정보 포함)

for i in range(5, 0, -1):            # 5부터 1까지 거꾸로 반복
    print(i)                         # 현재 숫자 출력
    t.sleep(1)                    # 1초 대기
print("발사!")                        # 카운트다운 종료 후 발사 메시지 출력

# random 모듈 - 난수 생성 관련 함수들 제공
import random
print(random.random())  # 0~1 사이 난수
print(random.randint(1,5))  # 1~5 사이 정수 난수

# math 모듈 - 수학 관련 함수들 제공
import math
print(math.pi)  # 파이 값
print(math.factorial(5))  # 팩토리얼 계산

# 5. 외부 모듈 설치 방법
"""
pip install 패키지명

Jupyter Notebook에서 설치 (!을 치면 콘솔창에서 입력하는 것과 같음.)
!pip install 패키지명
"""

# 6. 통계/데이터 분석용 주요 모듈
'''
데이터 분석, 통계
NumPy: 수학 및 과학 연산
Pandas: 데이터 분석
Matplotlib: 데이터 시각화
SciPy: 과학 계산
Scikit-learn: 머신러닝
인공지능
TensorFlow
PyTorch
Keras
웹 크롤링
BeautifulSoup
Selenium
'''

'''
주의사항
모듈 수정은 권장되지 않음 (수정 시 해당 컴퓨터에서만 사용 가능)
필요한 기능은 help() 함수로 확인 가능
Anaconda 사용 시 Navigator에서 패키지 관리 가능
'''

# 실습 예제: 로또 번호 생성기
import random
lotto = []
while True:
    temp = random.random()
    temp = temp * 100
    if temp >= 1 and temp < 46:
        lotto.append(int(temp))
        lotto = set(lotto)  # 중복 제거
        lotto = list(lotto)

    if len(lotto) == 6:
        break
print(lotto)

random.random()

# 효율적인 방법
print(random.sample(range(1,46),6))  # 1~45 사이 숫자 6개 무작위 선택

a = 7
b = 3
print("a // b =", a // b)

def greet(name):
    return f"안녕하세요, {name}님!"

print(greet("홍길동"))

score = 85
if score >= 90:
    print("A")
elif score >= 80:
    print("B")
else:
    print("C")